### ISSUE TITLE
Bug: "sum(up) > bool 0" returns sum(up) (expected "1")

### ISSUE THREAD

**Issue by vsile** [thanos-community/promql-engine#175] opened 2023-02-13 07:31 UTC
I tried to use --query.promql-engine=thanos in Thanos 0.30.2, but encountered with issue:

The query "sum(up) > bool 0" returns sum(up).
Without "--query.promql-engine=thanos" flag the query "sum(up) > bool 0" returns 1 (as expected).

**Comment by fpetkovski** [comment] 2023-02-13 07:52
Hi @vsile, thanks for reporting this. 

It seems like a bug which we fixed in https://github.com/thanos-community/promql-engine/pull/133, but haven't released yet. I tried running a querier from latest main with the thanos engine and it seems that the issue is not there anymore.

The next release candidate is planned for March 9th, but if you would like to move faster than that you can try running a querier from latest main.

**Comment by yeya24** [comment] 2023-02-20 03:43
Since the engine already fixed this issue, I will close this one. We just need to upgrade the version in Thanos.

**Closed by yeya24** 2023-02-20 03:43 UTC
